name: Release Esmerelda

on:
  push:
    branches:
      - rel
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Create Release ${{ github.event.pull_request.title }}
      uses: bfren/create-release@v1
      with:
        token: ${{ secrets.TOKEN }}
        branch: rel
        repo: RiversideValley/Esmerelda